require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require './lib/translator_to_braille'
require './lib/braille_alphabet'
require './lib/message_formatter'
# require './lib/english_translator'
# require './lib/english'
# require './lib/braille_formator'
