require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require './lib/translator_to_braille'
require './lib/braille_alphabet'
require './lib/message_formatter'
require './lib/translator_to_english'
require './lib/english_alphabet'
require './lib/braille_to_english_formatter'
